version: "3.7"
services:
  plex:
    container_name: plex
    image: plexinc/pms-docker
    hostname: plex
    domainname: ${DOMAIN}
    env_file:
      - ./env/global.env
    ports:
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32400:32400/tcp
      - 32469:32469/tcp
#      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    networks:
      - plex-net
    volumes:
      - PlexCFG:/config
      - PlexLib:/data
      - TMP:/transcode
    restart: unless-stopped

  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    #check at 3am only
    command: --cleanup --schedule "0 0 3 * * *"
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole
    hostname: pihole
    domainname: ${DOMAIN}
    env_file:
      - ./env/pihole.env
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 8888:80/tcp
      - 4444:443/tcp
    networks:
      - piHole-net
    volumes:
      - PiETC:/etc/pihole/
      - PiMasq:/etc/dnsmasq.d/
    restart: unless-stopped

  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    hostname: sonarr
    domainname: ${DOMAIN}
    env_file:
      - ./env/global.env
    ports:
      - 8989:8989
    networks:
      - torrent-net
      - plex-net
    volumes:
      - SonarrCFG:/config
      - PlexTV:/tv
      - Downloads:/downloads
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    hostname: radarr
    domainname: ${DOMAIN}
    env_file:
    - ./env/global.env
    ports:
      - 7878:7878
    networks:
      - torrent-net
      - plex-net
    volumes:
      - RadarrCFG:/config
      - PlexMovies:/movies
      - Downloads:/downloads
    restart: unless-stopped

  portainer:
    container_name: portainer
    image: portainer/portainer
    hostname: portainer
    domainname: ${DOMAIN}
    command: -H unix:///var/run/docker.sock
    env_file:
    - ./env/global.env
    ports:
      - 9000:9000
    networks:
      - port-net
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - PortainerDAT:/data
    restart: unless-stopped

  nginx:
    image: linuxserver/letsencrypt
    container_name: nginx
    cap_add:
      - NET_ADMIN
    env_file:
      - ./env/nginx.env
    volumes:
      - NginxCFG:/config
    ports:
      - 80:80
      - 443:443
    networks:
      - torrent-net
      - port-net
      - plex-net
      - piHole-net
    restart: unless-stopped

  ### VPN and Subcontainers

  vpn:
    container_name: vpn
    image: bubuntux/nordvpn
    hostname: vpn
    env_file:
      ./env/nordvpn.env
    ports:
      - 9117:9117 # jackett
      - 8112:8112 # deluge
      - 8118:8118 #
      - 58846:58846
      - 58946:58946
    networks:
      - torrent-net
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun
    restart: unless-stopped

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    depends_on:
      - vpn
    env_file:
      - ./env/global.env
    volumes:
      - DelugeCFG:/config
      - Downloads:/downloads
    network_mode: service:vpn
    restart: unless-stopped

  jackett:
    container_name: jackett
    image: linuxserver/jackett
    depends_on:
      - vpn
    env_file:
      - ./env/global.env
    volumes:
      - JackettCFG:/config
      - TMP:/downloads
    network_mode: service:vpn
    restart: unless-stopped

networks:
  piHole-net:
    driver: bridge
  torrent-net:
    driver: bridge
  port-net:
    driver: bridge
  plex-net:
    driver: bridge

volumes:
  RadarrCFG:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NAS},rw,bg,intr,soft,nolock
      device: ":${NASROOT}/radarr/config"
  SonarrCFG:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NAS},rw,bg,intr,soft,nolock
      device: ":${NASROOT}/sonarr/config"
  JackettCFG:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NAS},rw,bg,intr,soft,nolock
      device: ":${NASROOT}/jackett/config"
  DelugeCFG:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NAS},rw,bg,intr,soft,nolock
      device: ":${NASROOT}/deluge/config"
  Downloads:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NAS},rw,bg,intr,soft,nolock
        device: ":${NASROOT}/downloads"
  PlexTV:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NAS},rw,bg,intr,soft,nolock
        device: ":${NASROOT}/plex/library/television"
  PlexMovies:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NAS},rw,bg,intr,soft,nolock
        device: ":${NASROOT}/plex/library/movies"
  PlexLib:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NAS},rw,bg,intr,soft,nolock
        device: ":${NASROOT}/plex/library"
  PlexCFG:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NAS},rw,bg,intr,soft,nolock
        device: ":${NASROOT}/plex/config"
  NginxCFG:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NAS},rw,bg,intr,soft,nolock
        device: ":${NASROOT}/nginx/config"
  TMP:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NAS},rw,bg,intr,soft,nolock
        device: ":${NASROOT}/tmp"
  PiETC:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NAS},rw,bg,intr,soft,nolock
        device: ":${NASROOT}/pihole/etc-pihole/"
  PiMasq:
      driver: local
      driver_opts:
        type: nfs
        o: addr=${NAS},rw,bg,intr,soft,nolock
        device: ":${NASROOT}/pihole/etc-dnsmasq.d/"
  PortainerDAT:
    driver: local
    driver_opts:
      type: nfs
      o: addr=${NAS},rw,bg,intr,soft,nolock
      device: ":${NASROOT}/portainer/data"