---
version: '3.7'

x-driver_opts: &driverOpts
  type: nfs
  o: addr=10.10.10.252,rw,bg,intr,soft,nolock
x-nfs-driver: &nfsDriver
  driver: local

services:
#    forge:
#        container_name: forge
#        image: itzg/minecraft-server
#        hostname: forge
#        environment:
#            TYPE: CURSEFORGE
#            CF_SERVER_MOD: SkyFactory_4_Server_4.1.0.zip
#            EULA: TRUE
#            ENABLE_RCON: TRUE
#            RCON_PASSWORD: m1n3craft
#            RCON_PORT: 28016
#            CFG_DB_HOST: "http://localhost:3306"
#            CFG_DB_NAME: "minecraft"
#            CFG_DB_PASSWORD: "m1n3craft"
#        ports: ['25565:25565']
#        networks: [forge-net]
#        volumes: ['forgeMC:/data']
#        restart: unless-stopped
    bedrock:
        container_name: bedrock
        image: itzg/minecraft-bedrock-server
        hostname: bedrock
        environment:
            EULA: 'TRUE'
            GAMEMODE: survival
            DIFFICULTY: normal
            SERVER_NAME: 
        ports:
            - 19132:19132/udp
        networks: [forge-net]
        volumes: ['bedrockMC:/data']
        restart: unless-stopped
    vanilla:
        container_name: vanilla
        image: itzg/minecraft-server
        hostname: vanilla
        environment:
            EULA: 'TRUE'
            ENABLE_RCON: 'TRUE'
            RCON_PASSWORD: m1n3craft
            RCON_PORT: 28016
        ports: ['25567:25565']
        networks: [forge-net]
        volumes: ['./minecraft:/data']
        restart: unless-stopped


volumes:
    backupMC: 
        <<: *nfsDriver
        driver_opts:
            <<: *driverOpts
            device: ':/volume1/docker/minecraft/backups'
    bedrockMC:
        <<: *nfsDriver
        driver_opts:
            <<: *driverOpts
            device: ':/volume1/docker/bedrock-server'
    forgeMC:
        <<: *nfsDriver
        driver_opts:
            <<: *driverOpts
            device: ':/volume1/docker/forge/data'