version: '3'
  services:
    jackett:
      image: linuxserver/jackett
      container_name: jackett
      environment:
        - PUID=0
        - PGID=0
        - TZ=America/Toronto
      volumes:
        - /mnt/docker/jackett/config:/config
        - /var/tmp:/downloads
      ports:
        - 9117:9117
      restart: unless-stopped
    
    sonarr:
      image: linuxserver/sonarr
      container_name: sonarr
      environment:
        - PUID=0
        - GUID=0
        - TZ=America/Toronto
      volumes:
        - /mnt/docker/sonarr/config:/config
        - /mnt/docker/plex/library/television:/tv
        - /mnt/docker/downloads:/downloads
      ports:
        - 8989:8989
      restart: unless-stopped

    radarr:
        image: linuxserver/radarr
        container_name: radarr
        environment:
          - PUID=0
          - PGID=0
          - TZ=America/Toronto
        volumes:
          - /mnt/docker/radarr/config:/config
          - /mnt/docker/plex/library/movies:/movies
          - /mnt/docker/downloads:/downloads
        ports:
          - 7878:7878
        restart: unless-stopped

    traefik:
      image: traefik:latest
      command: --docker --docker.domain=beowulf.cc
      ports:
        - 80:80
        - 443:443
      networks:
        - proxy
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - /mnt/docker/traefik/traefik.toml:/traefik.toml
        - /mnt/docker/traefik/acme.json:/acme.json
      labels:
        - "traefik.frontend.rule=Host:traefik.beowulf.cc"
        - "traefik.port=8080"
      container_name: traefik
      restart: always




    ### VPN and Subcontainers

    vpn:
      image: bubuntux/nordvpn
      container_name: vpn
      cap_add:
        - NET_ADMIN
      volumes:
        - "/etc/localtime:/etc/localtime:ro"
      environment:
        - USER=<Your_VPN_User>
        - PASS=<Your_VPN_Password>
        - COUNTRY=Canada
        - CATEGORY=P2P
        - PROTOCOL=UDP
        - NETWORK=10.10.10.0/24
        - OPENVPN_OPTS=--pull-filter ignore "ping-restart" --ping-exit 180
      devices:
        - "/dev/net/tun"
      ports:
        - "8112:8112"
        - "8118:8118"
        - "58846:58846"
        - "58946:58946"
      networks: 

    deluge:
      image: linuxserver/deluge
      container_name: deluge
      depends_on:
        - vpn
      environment:
        - PUID=0
        - PGID=0
        - TZ=America/Toronto
      network_mode: "service:vpn"
      labels:
        traefik.enable: "true"
        traefik.frontend.headers.customResponseHeaders: "X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex"
        traefik.frontend.redirect.entryPoint: "https"
        traefik.frontend.rule: "Host:deluge.beowulf.cc,artemis.beowulf.cc"
        traefik.port: "8112"
      volumes:
        - "/mnt/docker/deluge/config:/config"
        - "/mnt/docker/deluge/unionfs:/unionfs"
        - "/mnt/docker/deluge:/mydata"
      mem_limit: 4096m
      restart: unless-stopped




#networks
# plex
# sonarr
# radarr
# jackett
# traefik?

  networks:
    proxy:
      external: true
    default:
      external:
        name: beowulf