---
version: "3.7"

x-defaultCONF: &defaultCONF
  deploy:
    replicas: 1
    update_config:
      parallelism: 0
      failure_action: rollback
    rollback_config:
      parallelism: 0
  env_file: [./env/global.env]
x-driver_opts: &driverOpts
  type: nfs
  o: addr=10.10.10.252,rw,bg,intr,soft,nolock
x-nfs-driver: &nfsDriver
  driver: local

services:
  minecraft:
    image: itzg/minecraft-server
    hostname: forge
    env_file: [./env/forge.env]
    ports:
      - "28016:28016"
      - "25565:25565"
    networks: [forge-net]
    volumes: [forge_mc:/data]
  rcon:
    image: itzg/rcon
    ports:
      - "4326:4326"
      - "4327:4327"
    networks: [forge-net]
    volumes: [rcon:/opt/rcon-web-admin/db]
  plex:
    image: plexinc/pms-docker
    <<: *defaultCONF
    ports:
      - "3005:3005"
      - "8324:8324"
      - "32400:32400"
      - "32469:32469"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412-32414:32412-32414/udp"
    networks: [plex-net]
    volumes: 
      - plex_cfg:/config
      - plex_lib:/data
      - tmp:/transcode
  watchtower:
    image: v2tec/watchtower
    command: --cleanup --schedule "0 0 3 * * *"
    <<: *defaultCONF
    volumes: [/var/run/docker.sock:/var/run/docker.sock]
  sonarr:
    image: linuxserver/sonarr
    <<: *defaultCONF
    ports: ["8989:8989"]
    networks:
      - torrent-net
      - plex-net
    volumes:
      - sonarr_cfg:/config
      - plex_tv:/tv
      - downloads:/downloads
  radarr:
    image: linuxserver/radarr
    <<: *defaultCONF
    ports: ["7878:7878"]
    networks:
      - torrent-net
      - plex-net
    volumes:
      - radarr_cfg:/config
      - plex_movies:/movies
      - downloads:/downloads
  portainer:
    image: portainer/portainer
    command: -H unix:///var/run/docker.sock
    <<: *defaultCONF
    ports: ["9000:9000"]
    networks: [port-net]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_dat:/data
  nginx:
    image: linuxserver/letsencrypt
    <<: *defaultCONF
    env_file: [./env/nginx.env]
    ports:
      - "80:80"
      - "443:443"
    networks:
      - torrent-net
      - port-net
      - plex-net
      - forge-net
    volumes: [nginx_cfg:/config]
  vpn:
    image: bubuntux/nordvpn
    <<: *defaultCONF
    env_file: [./env/nordvpn.env]  
    ports:
      - "9117:9117" # jackett
      - "8112:8112" # deluge
      - "8118:8118" # vpn
      - "58846:58846"
      - "58946:58946"
    networks: [torrent-net]
    devices: [/dev/net/tun]
  deluge:
    image: linuxserver/deluge
    <<: *defaultCONF
    volumes:
      - deluge_cfg:/config
      - downloads:/downloads
    network_mode: service:vpn
  jackett:
    image: linuxserver/jackett
    <<: *defaultCONF
    volumes:
      - jackett_cfg:/config
      - tmp:/downloads
    network_mode: service:vpn

networks:
  torrent-net:
  port-net:
  plex-net:
  forge-net:

volumes:
  forge_mc: 
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/forge/data"
  rcon: 
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/rcon/db"
  radarr_cfg: 
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/radarr/config"
  sonarr_cfg:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/sonarr/config"
  jackett_cfg:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/jackett/config"
  deluge_cfg:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/deluge/config"
  downloads:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/downloads"
  plex_tv:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/plex/library/television"
  plex_movies:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/plex/library/movies"
  plex_lib:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/plex/library"
  plex_cfg:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/plex/config"
  nginx_cfg:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/nginx/config"
  tmp:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/tmp"
  portainer_dat:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/portainer/data"
