---
version: "3.7"

x-defaultCONF: &defaultCONF
  domainname: beowulf.cc
  restart: always
  env_file:
  - ./env/global.env
x-driver_opts: &driverOpts
    type: nfs
    o: addr=10.10.10.252,rw,bg,intr,soft,nolock
x-nfs-driver: &nfsDriver
  driver: local

services:
  minecraft:
    container_name: forge
    image: itzg/minecraft-server
    hostname: forge
    <<: *defaultCONF
    env_file: [./env/forge.env]
    ports:
      - "28016:28016"
      - "25565:25565"
    networks: [forge-net]
    volumes: [forgeMC:/data]
  rcon:
    container_name: rcon
    image: itzg/rcon
    hostname: rcon
    <<: *defaultCONF
    ports:
      - "4326:4326"
      - "4327:4327"
    networks: [forge-net]
    volumes: [rcon:/opt/rcon-web-admin/db]
  plex:
    container_name: plex
    image: plexinc/pms-docker
    hostname: plex
    <<: *defaultCONF
    ports:
      - "3005:3005"
      - "8324:8324"
      - "32400:32400"
      - "32469:32469"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412-32414:32412-32414/udp"
    networks: [plex-net]
    volumes:
      - PlexCFG:/config
      - PlexLib:/data
      - TMP:/transcode
  watchtower:
    container_name: watchtower
    image: v2tec/watchtower
    command: --cleanup --schedule "0 0 3 * * *"
    <<: *defaultCONF
    volumes: [/var/run/docker.sock:/var/run/docker.sock]
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    hostname: sonarr
    <<: *defaultCONF
    ports: ["8989:8989"]
    networks:
      - torrent-net
      - plex-net
    volumes:
      - SonarrCFG:/config
      - PlexTV:/tv
      - Downloads:/downloads
  radarr:
    container_name: radarr
    image: linuxserver/radarr
    hostname: radarr
    <<: *defaultCONF
    ports: ["7878:7878"]
    networks:
      - torrent-net
      - plex-net
    volumes:
      - RadarrCFG:/config
      - PlexMovies:/movies
      - Downloads:/downloads
  portainer:
    container_name: portainer
    image: portainer/portainer
    hostname: portainer
    command: -H unix:///var/run/docker.sock
    <<: *defaultCONF
    ports: ["9000:9000"]
    networks: [port-net]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - PortainerDAT:/data
  nginx:
    image: linuxserver/letsencrypt
    container_name: nginx
    <<: *defaultCONF
    env_file: [./env/nginx.env]
    ports:
      - "80:80"
      - "443:443"
    networks:
      - torrent-net
      - port-net
      - plex-net
      - forge-net
    volumes: [NginxCFG:/config]
    cap_add: [NET_ADMIN]
  vpn:
    container_name: vpn
    image: bubuntux/nordvpn
    hostname: vpn
    <<: *defaultCONF
    env_file: [./env/nordvpn.env]  
    ports:
      - "9117:9117" # jackett
      - "8112:8112" # deluge
      - "8118:8118" # vpn
      - "58846:58846"
      - "58946:58946"
    networks: [torrent-net]
    devices: [/dev/net/tun]
    cap_add: [NET_ADMIN]
  deluge:
    container_name: deluge
    image: linuxserver/deluge
    <<: *defaultCONF
    volumes:
      - DelugeCFG:/config
      - Downloads:/downloads
    network_mode: service:vpn
    depends_on: [vpn]
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    <<: *defaultCONF
    volumes:
      - JackettCFG:/config
      - TMP:/downloads
    network_mode: service:vpn
    depends_on: [vpn]
    
networks:
  torrent-net:
  port-net:
  plex-net:
  forge-net:

volumes:
  forgeMC: 
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/forge/data"
  rcon: 
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/rcon/db"
  RadarrCFG: 
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/radarr/config"
  SonarrCFG:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/sonarr/config"
  JackettCFG:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/jackett/config"
  DelugeCFG:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/deluge/config"
  Downloads:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/downloads"
  PlexTV:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/plex/library/television"
  PlexMovies:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/plex/library/movies"
  PlexLib:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/plex/library"
  PlexCFG:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/plex/config"
  NginxCFG:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/nginx/config"
  TMP:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/tmp"
  PortainerDAT:
    <<: *nfsDriver
    driver_opts:
      <<: *driverOpts
      device: ":/volume1/docker/portainer/data"