version: "3.7"
services:
  jackett:
    container_name: jackett
    image: linuxserver/jackett
    env_file:
      - ./env/global.env
    ports:
      - 9117:9117
    volumes:
      - ${DOCKER}/jackett/config:/config
      - /var/tmp:/downloads
    restart: unless-stopped

  plex:
    container_name: plex
    image: plexinc/pms-docker
    env_file:
      - ./env/global.env
      #PLEX_CLAIM: [claimtoken]
      #Advertise_IP: 
    ports:
      - 32400:32400/tcp
      - 3005:3005/tcp
      - 8324:8324/tcp
      - 32469:32469/tcp
      - 1900:1900/udp
      - 32410:32410/udp
      - 32412:32412/udp
      - 32413:32413/udp
      - 32414:32414/udp
    volumes:
      - ${DOCKER}/plex/config:/config
      - ${DOCKER}/plex/library:/data
      - ${DOCKER}/plex/transcode:/transcode
    restart: unless-stopped

  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    env_file:
      - ./env/pihole.env
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      - 81:80/tcp
      - 444:443/tcp
    volumes:
      - ${DOCKER}/pihole/etc-pihole/:/etc/pihole/
      - ${DOCKER}/pihole/etc-dnsmasq.d/:/etc/dnsmasq.d/
    #cap_add:   # enable for DHCP
    #  - NET_ADMIN
    restart: unless-stopped
  
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr
    env_file:
      - ./env/global.env
    ports:
      - 8989:8989
    volumes:
      - ${DOCKER}/sonarr/config:/config
      - ${DOCKER}/plex/library/television:/tv
      - ${DOCKER}/downloads:/downloads
    restart: unless-stopped

  radarr:
    container_name: radarr
    image: linuxserver/radarr
    env_file:
    - ./env/global.env
    ports:
      - 7878:7878
    volumes:
      - ${DOCKER}/radarr/config:/config
      - ${DOCKER}/plex/library/movies:/movies
      - ${DOCKER}/downloads:/downloads
    restart: unless-stopped

  traefik:
    container_name: traefik
    image: traefik:1.7
    #image: traefik:latest
    env_file:
      ./env/traefik.env
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ${DOCKER}/traefik/traefik.toml:/etc/traefik/traefik.toml
      - ${DOCKER}/traefik/acme.json:/acme.json
      #- ${DOCKER}/traefik/traefik.yml:/traefik.yml
    #command: --providers.docker
    #networks:
    #  - proxy
    labels:
      - traefik.enabled=true
    restart: unless-stopped




  ### VPN and Subcontainers

  vpn:
    container_name: vpn
    image: bubuntux/nordvpn
    env_file:
      ./env/nordvpn.env
    ports:
      - 8112:8112
      - 8118:8118
      - 58846:58846
      - 58946:58946
    cap_add:
      - NET_ADMIN
    #volumes:
    #  - /etc/localtime:/etc/localtime:ro
    devices:
      - /dev/net/tun
    restart: unless-stopped

  deluge:
    container_name: deluge
    image: linuxserver/deluge
    depends_on:
      - vpn
    env_file:
      - ./env/global.env
    volumes:
      - ${DOCKER}/deluge/config:/config
      - ${DOCKER}/deluge/unionfs:/unionfs
      - ${DOCKER}/deluge:/mydata
    network_mode: service:vpn
    labels:
      traefik.enable: true
      traefik.frontend.headers.customResponseHeaders: X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex
      traefik.frontend.redirect.entryPoint: https
      traefik.frontend.rule: ${URL_DELUGE}
      traefik.port: 8112
    restart: unless-stopped
      
#networks:
#  beowulf:
#    external: true
#  proxy:
#    external: true