---
version: '3.7'

x-driver_opts: &driverOpts
  type: nfs
  o: addr=10.10.10.252,rw,bg,intr,soft,nolock
x-nfs-driver: &nfsDriver
  driver: local

services:
#    forge:
#        container_name: forge
#        image: itzg/minecraft-server
#        hostname: forge
#        environment:
#            TYPE: CURSEFORGE
#            CF_SERVER_MOD: SkyFactory_4_Server_4.1.0.zip
#            EULA: TRUE
#            ENABLE_RCON: TRUE
#            RCON_PASSWORD: m1n3craft
#            RCON_PORT: 28016
#            CFG_DB_HOST: "http://localhost:3306"
#            CFG_DB_NAME: "minecraft"
#            CFG_DB_PASSWORD: "m1n3craft"
#        ports: ['25565:25565']
#        networks: [forge-net]
#        volumes: ['forgeMC:/data']
#        restart: unless-stopped
    bedrockCreative:
        container_name: bedrockCreative
        image: itzg/minecraft-bedrock-server
        hostname: bedrockCreative
        environment:
            EULA: 'TRUE'
            DIFFICULTY: normal
            GAMEMODE: creative
            SERVER_NAME: 'Creativo'
            SERVER_PORT: '19134'
            ALLOW_CHEATS: 'true'
            MAX_PLAYERS: '7'
            LEVEL_NAME: 'Creativo'
        ports:
            - 19134:19134/udp
            - 19134:19134/tcp
        networks: [forge-net]
        volumes: ['bedrockCreativeMC:/data']
        restart: unless-stopped
    bedrock:
        container_name: bedrock
        image: itzg/minecraft-bedrock-server
        hostname: bedrock
        environment:
            EULA: 'TRUE'
            GAMEMODE: survival
            DIFFICULTY: normal
            SERVER_NAME: 
        ports:
            - 19132:19132/udp
            - 19132:19132/tcp
        networks: [forge-net]
        volumes: ['bedrockMC:/data']
        restart: unless-stopped
    vanilla:
        container_name: vanilla
        image: itzg/minecraft-server
        hostname: vanilla
        environment:
            EULA: 'TRUE'
            ENABLE_RCON: 'TRUE'
            RCON_PASSWORD: m1n3craft
            RCON_PORT: 28016
        ports: ['25567:25565']
        networks: [forge-net]
        volumes: ['./minecraft:/data']
        restart: unless-stopped
    vanillaBAK:
        container_name: vanillaBAK
        image: itzg/mc-backup
        environment:
            BACKUP_NAME: 'vanilla'
            BACKUP_INTERVAL: '24h'
            PRUNE_BACKUPS_DAYS: 7
            BACKUP_METHOD: 'tar'
            DEST_DIR: '/backups'
            LINK_LATEST: 'false'
            INITIAL_DELAY: 0
            RCON_HOST: vanilla
            RCON_PORT: 28016
            RCON_PASSWORD: m1n3craft
        networks: [forge-net]
        volumes:
            - 'backupMC:/backups'
            - './minecraft:/data'
    terraria:
        container_name: 'terraria'
        image: ryshe/terraria
        command: '-world /world/The_Unlawful_Crown_of_Teeth.wld'
        ports: ['7777:7777']
        networks: [terraria-net]
        volumes: [terraria:/world]

networks:
    terraria-net:

volumes:
    backupMC: 
        <<: *nfsDriver
        driver_opts:
            <<: *driverOpts
            device: ':/volume1/docker/minecraft/backups'
    bedrockMC:
        <<: *nfsDriver
        driver_opts:
            <<: *driverOpts
            device: ':/volume1/docker/bedrock-server'
    bedrockCreativeMC:
        <<: *nfsDriver
        driver_opts:
            <<: *driverOpts
            device: ':/volume1/docker/bedrockCreative'
    forgeMC:
        <<: *nfsDriver
        driver_opts:
            <<: *driverOpts
            device: ':/volume1/docker/forge/data'
    terraria:
        <<: *nfsDriver
        driver_opts: 
            <<: *driverOpts
            device: ':/volume1/docker/terraria'