## traefik.yml

global:
  checkNewVersion: false
  sendAnonymousUsage: false
serversTransport:
  insecureSkipVerify: true
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
  traefik:
    address: ":8080"
providers:
  docker:
    watch: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    defaultRule: "Host(`beowulf.cc`)"
    # defaultRule: "Host(`{{ trimPrefix `/` .Name }}.docker.localhost`)"
api:
  insecure: true
  dashboard: true
  debug: false

  certificatesResolvers:
  sample:
    acme:
      # ...
      dnsChallenge:
        provider: cloudflare
        delayBeforeCheck: 0