logLevel = "ERROR" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
InsecureSkipVerify = true 
defaultEntryPoints = ["https", "http"]

[api]
    entryPoint = "traefik"
    dashboard = true
    address = ":8080"

# Force HTTPS
[entryPoints]
    [entryPoints.http]
        address = ":80"
            [entryPoints.http.redirect]
                entryPoint = "https"
    [entryPoints.https]
        address = ":443"
    [entryPoints.https.tls]

[file]
    #watch = true
    #filename = "/etc/traefik/rules.toml"

[acme]
    email = "grendel@beowulf.cc"
    storage="/etc/traefik/acme/acme.json"
    entryPoint = "https"
    acmeLogging=true 
    onDemand = false #create certificate when container is created
[acme.dnsChallenge]
    provider = "cloudflare"
    delayBeforeCheck = 300
[[acme.domains]]
    main = "beowulf.cc"
[[acme.domains]]
    main = "*.beowulf.cc"
   
[docker]
    endpoint = "unix:///var/run/docker.sock"
    domain = "beowulf.cc"
    watch = true
    exposedbydefault = false